[package]
name = "gbemulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
phf = {version = "0.11.2", features = ["macros"]}
sdl2 = "0.37.0"

[unstable]
